name: Run Unit Tests

on:
  push:
    branches:
      
main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    
name: Checkout repository
    uses: actions/checkout@v2

    
name: Set up Node.js
    uses: actions/setup-node@v2
    with:
      node-version: '14'

    
name: Install dependencies
    run: npm install

    
name: Run unit tests
    run: npm test

    
name: Display test results
    run: cat test-results.txt  # Supposons que vos tests écrivent leurs résultats dans un fichier test-results.txt
